---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket
  region: ap-southeast-1
  version: 1.21
  
managedNodeGroups:
  - name: bottlerocket-nodegroup
    instanceType: m5.xlarge
    minSize: 1
    maxSize: 4
    desiredCapacity: 1
    volumeType: gp3
    spot: true
    amiFamily: Bottlerocket
    labels: { role: br-worker }
    tags:
       nodegroup-type: Bottlerocket 
    ssh:
      allow: true
      publicKeyName: eks_bottlerocket 



# eksctl create nodegroup --cluster bottlerocket-cluster -f bottlerocket-managed-nodegroup.yaml

# List node

# kubectl get nodes -o=custom-columns=NODE:.metadata.name,ARCH:.status.nodeInfo.architecture,OS-Image:.status.nodeInfo.osImage,OS:.status.nodeInfo.operatingSystem

# aws ec2 describe-instances --query Reservations[*].Instances[*].[InstanceId] --output text
